In [69]:
import pandas as pd

In [70]:
df = pd.read_csv("../data/hasil_scraping_demo/fix_scarap/all_data.csv")

In [71]:
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1962164401047584943,Sun Aug 31 14:43:43 +0000 2025,5677,Menyikapi pernyataan Prabowo bersama dengan pi...,1962164401047584943,https://pbs.twimg.com/ext_tw_video_thumb/19621...,NaN,in,NaN,54,87,3660,https://x.com/undefined/status/196216440104758...,222346474,NaN
1,1962095963067281680,Sun Aug 31 10:11:46 +0000 2025,7435,Saudara-saudari sebangsa dan setanah air Negar...,1962095963067281680,https://pbs.twimg.com/media/GzrD3wkbAAARd5J.jpg,NaN,in,NaN,4037,4287,1575,https://x.com/undefined/status/196209596306728...,40580714,NaN
2,1961314767135793290,Fri Aug 29 06:27:34 +0000 2025,14161,Ringkasan Pernyataan Presiden: 1. Menuduh demo...,1961314767135793290,https://pbs.twimg.com/amplify_video_thumb/1961...,NaN,in,NaN,2003,709,14116,https://x.com/undefined/status/196131476713579...,1850558971779956736,NaN
3,1961739270571671590,Sat Aug 30 10:34:24 +0000 2025,4806,Musuh kita bukan fasilitas umum. Bukan perbeda...,1961739270571671590,https://pbs.twimg.com/amplify_video_thumb/1961...,NaN,in,NaN,34,65,1939,https://x.com/undefined/status/196173927057167...,1644664050868178944,NaN
4,1961681299988779366,Sat Aug 30 06:44:02 +0000 2025,306,R E Q U I E M ● Brutalitas aparat bukan saja p...,1961681299988779366,https://pbs.twimg.com/ext_tw_video_thumb/19616...,NaN,in,NaN,1,30,93,https://x.com/undefined/status/196168129998877...,1159689173340585984,NaN

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      4668 non-null   int64
 1   created_at               4668 non-null   object
 2   favorite_count           4668 non-null   int64
 3   full_text                4668 non-null   object
 4   id_str                   4668 non-null   int64
 5   image_url                1940 non-null   object
 6   in_reply_to_screen_name  553 non-null    object
 7   lang                     4668 non-null   object
 8   location                 0 non-null      float64
 9   quote_count              4668 non-null   int64
 10  reply_count              4668 non-null   int64
 11  retweet_count            4668 non-null   int64
 12  tweet_url                4668 non-null   object
 13  user_id_str              4668 non-null   int64
 14  username                 0 non-null      float64
dtypes: float64(2), int64(7), object(6)
memory usage: 547.2+ KB

In [ ]:
import re 

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)  
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'RT[\s]+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'@[A-Za-z0-9_]+|#[A-Za-z0-9_]+|[^A-Za-z\s]', '', text)
    text = re.sub(r'\b[a-zA-Z](?:\s+[a-zA-Z])+\b', lambda m: m.group().replace(" ", ""), text)

    return text

def extract_hashtags(text):
    return re.findall(r'#\w+', text)

def clean_data(df):
    df.drop_duplicates(inplace=True)
    df.drop(columns=["conversation_id_str", "id_str", "location" ,"user_id_str", "username","tweet_url", "image_url", "lang", "in_reply_to_screen_name"], inplace=True)
    df['hashtags'] = df['full_text'].apply(extract_hashtags)
    df['cleaned_text'] = df['full_text'].apply(clean_text)
    df['cleaned_text'] = df['cleaned_text'].str.lower()
    return df

In [76]:
df_cleaned = clean_data(df.copy())

In [77]:
df_cleaned.head()

,created_at,favorite_count,full_text,quote_count,reply_count,retweet_count,hashtags,cleaned_text
0,Sun Aug 31 14:43:43 +0000 2025,5677,Menyikapi pernyataan Prabowo bersama dengan pi...,54,87,3660,[],menyikapi pernyataan prabowo bersama dengan pi...
1,Sun Aug 31 10:11:46 +0000 2025,7435,Saudara-saudari sebangsa dan setanah air Negar...,4037,4287,1575,[],saudarasaudari sebangsa dan setanah air negara...
2,Fri Aug 29 06:27:34 +0000 2025,14161,Ringkasan Pernyataan Presiden: 1. Menuduh demo...,2003,709,14116,[],ringkasan pernyataan presiden menuduh demonst...
3,Sat Aug 30 10:34:24 +0000 2025,4806,Musuh kita bukan fasilitas umum. Bukan perbeda...,34,65,1939,[],musuh kita bukan fasilitas umum bukan perbedaa...
4,Sat Aug 30 06:44:02 +0000 2025,306,R E Q U I E M ● Brutalitas aparat bukan saja p...,1,30,93,[],r e q u i e m brutalitas aparat bukan saja pr...

In [78]:
df_cleaned.isnull().sum()

created_at        0
favorite_count    0
full_text         0
quote_count       0
reply_count       0
retweet_count     0
hashtags          0
cleaned_text      0
dtype: int64

In [60]:
df_cleaned['hashtags'].value_counts()

hashtags
[]                                                      1054
[#DesakPrabowoBubarkanDPR, #DesakPrabowoBubarkanDPR]      14
[#polisipembunuh]                                         14
[#intinyadeh]                                              6
[#Polhuk, #AdadiKompas]                                    6
                                                        ...
[#DPR]                                                     1
[#Indonesia]                                               1
[#DPRRI, #Demo]                                            1
[#KaburAjaDulu]                                            1
[#Demo, #BubarkanDPR]                                      1
Name: count, Length: 92, dtype: int64

In [61]:
df.to_csv("../data/hasil_scraping_demo/fix_scarap/cleaned_data.csv", index=False)